fel: Introduce 'sid-dump'
linux-sunxi/sunxi-tools pull request #189
Opened 2023-02-10 09:34 UTC by qianfan-Zhao

A sample output from allwinner R40:

```console
$ ./sunxi-fel sid-dump
chipid          1300000c 02404700 79350400 5c761e0c
in              00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
ssk             00000000 00000000 00000000 00000000
thermal         08320834
ft_zone         00000000 00000000
tvout           010002b0 00f7029b 00f9029f 00fb02a5
rssk            00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
hdcp_hash       00000000 00000000 00000000 00000000
reserved        00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
                00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
                00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
                00000000 00000000 00000000 00000000
```

2023-02-10 22:44 UTC, apritzel requested changes
Hi Qianfan,
thanks for the patch, looks like a useful addition!
Can you please add some more text to the commit message, based on the text you used for the pull request?
And we would need the new command mentioned in the internal help text, ideally also in the manpage.
Some comments inside.

2023-02-10 22:44 UTC, apritzel commented on fel.c
> +		if (count > sizeof(buffer) / sizeof(buffer[0])) {
In common.h we have ARRAY_SIZE() for this. But in general this looks a bit odd to check this at all, since there is an upper limit (the 2KB SID storage size) and the input size comes from an internal struct, so we don't need to defend against user input.

2023-02-10 22:44 UTC, apritzel commented on fel_lib.c
> +	if (!dev->soc_info->sid_base) {
This check looks unnecessary, since we check this before calling this function.

2023-02-10 22:44 UTC, apritzel commented on fel_lib.c
> +			result[i] = 0;
First this would be a job for memset(). But why would we want to clear the result before we bail out? In fact I would expect a function to not touch a result buffer in case of an early error. Also the caller doesn't seem to need this, so remove that clearing part.

2023-02-10 22:44 UTC, apritzel commented on soc_info.c
> +
stray extra line

2023-02-11 02:25 UTC, qianfan-Zhao commented on fel.c
> +		if (count > sizeof(buffer) / sizeof(buffer[0])) {
done

2023-02-11 02:25 UTC, qianfan-Zhao commented on fel_lib.c
> +	if (!dev->soc_info->sid_base) {
OK, removed

2023-02-11 02:26 UTC, qianfan-Zhao commented on fel_lib.c
> +			result[i] = 0;
Both the check for sid_base and the  clear function are removed now.

2023-02-14 00:51 UTC, apritzel approved these changes
Thanks for the quick changes, looks alright now. Tested on a Bananapi M2 Berry. I also tested with some A64 and H6 maps, will send them later.
I will let this sit for a few more days, in case people have comments.

2023-02-14 01:27 UTC, smaeul commented on fel_lib.c
> +		    + dev->soc_info->sid_offset + offset, result, count);
Should this use the register readout method on SoCs where that is required?

2023-02-14 05:59 UTC, qianfan-Zhao commented on fel_lib.c
> +		    + dev->soc_info->sid_offset + offset, result, count);
It's the better. I've considered it, but it's too hard to write assembly code.

2023-02-20 10:58 UTC, apritzel commented on fel_lib.c
> +		    + dev->soc_info->sid_offset + offset, result, count);
So it looks like `fel_get_sid_registers()` can be easily extended to read <n> registers from offset <x> instead of 4 registers from offset 0. Then we could just extend `fel_get_sid_root_key()` to allow parameters, and use that for both sid-dump and for `aw_fel_print_sid()`, avoiding a new function.
@qianfan-Zhao do you want to do this? If not, I can do it in a follow up patch.

2023-02-21 10:26 UTC, qianfan-Zhao commented on fel_lib.c
> +		    + dev->soc_info->sid_offset + offset, result, count);
@apritzel It is hard to me. Could you please submit some patchs after this pr merged?

2023-02-21 10:31 UTC, apritzel commented on fel_lib.c
> +		    + dev->soc_info->sid_offset + offset, result, count);
Ok, will do.

2023-02-21 11:00 UTC, apritzel reviewed
Just two minor things I noticed about the output formatting.

2023-02-21 11:00 UTC, apritzel commented on fel.c
> +				printf("%-16s", "");
Just saw this on a final inspection: can you merge those two into one line:

    printf("\n%-16s", "");
Then you can get rid of the brackets as well.

2023-02-21 11:00 UTC, apritzel commented on fel.c
> +			printf("%08x ", buffer[i]);
if you decrease the indent from 16 to 15 in the tow lines above, you can put the space here first, before the number, and avoid a trailing space on the last word.

2023-02-22 01:34 UTC, qianfan-Zhao commented on fel.c
> +			printf("%08x ", buffer[i]);
done

2023-02-22 01:34 UTC, qianfan-Zhao commented on fel.c
> +				printf("%-16s", "");
done

2023-02-22 11:50 UTC, merged