add a133 support
linux-sunxi/sunxi-tools pull request #192
Opened 2023-03-15 13:02 UTC by baidxi

add a133 support

2023-03-17 01:24 UTC, apritzel requested changes
Hi,

thanks for sending this! I had something similar here locally, so happy to test and review.

2023-03-17 01:24 UTC, apritzel commented on soc_info.c
> +		.swap_buffers = a133_sram_swap_buffers,
With the above changes, you might not need a separate swap_buffers array, instead I ended up re-using v831_sram_swap_buffers, which just stores away the IRQ FEL stack. We might want to use a higher address, though, to get more usable SRAM.

2023-03-21 01:44 UTC, baidxi commented on soc_info.c
> +		.spl_addr     = 0x24000,
start at 0x20000 only 4K is valid, at very early. so change to SRAM C location

2023-03-21 22:39 UTC, apritzel commented on soc_info.c
> +		.spl_addr     = 0x24000,
What makes you think so? I dumped all the first 16KB, twice, then wrote something to 0x22000 (or 0x23000), and read that back, with the rest untouched. So everything from 0x20000 to 0x23fff is perfect SRAM, available early. This is also mentioned in the manual: "16K(support Byte operation, clock source is AHB1)". So there is no mentioning of this being sparse, or restricted, or borrowed to another peripheral.
If you tried writing something to 0x21000 and it crashed: This is due to this area being used by the BROM FEL routine (for the IRQ stack), you must not touch the area between 0x21000 and 0x21400. You mention this yourself in the patch, by backing up this part.
So do you have any other insight into why there would be only 4K available?
As mentioned before, we cannot easily change this location to our liking, as this has to match where the BROM loads to.

2023-03-30 11:38 UTC, closed without merging