fel: Add support for allwinner T7
linux-sunxi/sunxi-tools pull request #204
Opened 2024-01-02 10:43 UTC by qianfan-Zhao

uart0-helloworld-sdcard can work with this patch:

```console
./sunxi-fel --verbose spl uart0-helloworld-sdboot.sunxi
Stack pointers: sp_irq=0x00022000, sp=0x00025E08
MMU is not enabled by BROM
=> Executing the SPL... done.
```

And next is the uart console's log:

```
Hello from Allwinner T7!
Returning back to FEL.
```

2024-01-05 08:36 UTC, apritzel requested changes
That looks mostly good, thanks for sending this! Some comments inside.

2024-01-05 08:36 UTC, apritzel commented on soc_info.c
> + *                                          when read back
Does the T7 have an OpenRISC management core? Then this will probably be its exception vector area, where only one word in every 256 byte region is writable, as seen in the other OpenRISC SoCs.

2024-01-05 08:36 UTC, apritzel commented on soc_info.c
> +	{ .buf1 = 0x21C00, .buf2 = 0x4d800, .size = 0x0400 },
Do we need such a large stack? Do you know the stack pointer value?

2024-01-05 08:36 UTC, apritzel commented on soc_info.c
> +		.thunk_addr   = 0x4d200, .thunk_size = 0x200,
There seems to be a gap between this thunk area and the swap buffers. Is that intentional? Can we move this area here up to end at the swap buffer's start?

2024-01-05 08:36 UTC, apritzel commented on uart0-helloworld-sdboot.c
> +	} else if (soc_is_t7()) {
That looks to be the same as the A64. Can you please double check and then just add soc_is_t7() to the existing A64 check?

2024-01-05 10:34 UTC, qianfan-Zhao commented on soc_info.c
> + *                                          when read back
I had not find the OpenRISC core in the datasheet.  I had write 16KB zero data to this section and then readback, next is the new data:

```
$ hexdump -C 2.bin
00000000  00 00 00 00 00 00 00 15  00 00 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000100  00 00 00 00 00 00 00 15  00 00 00 00 00 00 00 00  |................|
00000110  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000200  00 00 00 00 00 00 00 15  00 00 00 00 00 00 00 00  |................|
00000210  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
...
```

Maybe there only one word in every 256 byte region is not writable. And I don't known what the means of 0x15.

2024-01-05 11:05 UTC, qianfan-Zhao commented on soc_info.c
> +	{ .buf1 = 0x21C00, .buf2 = 0x4d800, .size = 0x0400 },
I had write a tool like #130, write 1K random data everytime and then readback, when I write data to 0x21c00 the bootROM will hang. So I think this section size is 1K, maybe reducing the amount of data written each time will get a  more accurate results, but that's not important.

when startting u-boot-spl in verbose mode, it will print the stack pointer value:

```
./sunxi-fel --verbose spl uart0-helloworld-sdboot.sunxi
Stack pointers: sp_irq=0x00022000, sp=0x00025E08
MMU is not enabled by BROM
=> Executing the SPL... done.
```

the *sp_irq* value can match it.

2024-01-05 11:22 UTC, qianfan-Zhao commented on soc_info.c
> +		.thunk_addr   = 0x4d200, .thunk_size = 0x200,
No enough reason. The swap buffer is started at 0x4d800 and I make the thunk address before swap buffer. And reserve some space if we need extended the thunk_size in the future.

2024-01-05 11:23 UTC, qianfan-Zhao commented on uart0-helloworld-sdboot.c
> +	} else if (soc_is_t7()) {
Sure.

2024-01-05 19:04 UTC, apritzel commented on soc_info.c
> + *                                          when read back
Yes,that's exactly the OpenRISC exception vector pattern we see in the other SoCs, compare here: https://linux-sunxi.org/A64/Memory_map

2024-01-05 19:22 UTC, apritzel commented on soc_info.c
> +	{ .buf1 = 0x21C00, .buf2 = 0x4d800, .size = 0x0400 },
Thanks for the stack pointers! Yes, the IRQ stack looks correct, both the size and location. I was wondering about the normal stack, though. Can you dump the BootROM somewhere? The initial FEL stack pointers are pretty easy to find in the disassembly, then we could reserve 5K down from there, to be on the safe side, and make sure the 0x25e08 is in that region.

2024-01-05 19:25 UTC, apritzel commented on soc_info.c
> +		.thunk_addr   = 0x4d200, .thunk_size = 0x200,
All other SoCs use 0x200, and the current code uses much less than that, If we would need more, we would need to change the value for all other SoCs, too. So there is no reason to go beyond 512 bytes, or to reserve space already.

2024-01-05 19:28 UTC, apritzel commented on soc_info.c
> + *                                          when read back
To elaborate: the first word is writable: that receives the branch instruction containing the target address of the exception handler. The 0x15000000 is the hardcoded NOP needed for the delay slot. The rest of each 256 byte region is not implemented and hardwired to 0.

2024-01-08 06:57 UTC, qianfan-Zhao commented
Hi @apritzel , the attachment is the N-BROM dump with https://github.com/DrSchottky/Allwinner-BROM-dumper:

```console
$ ./dump 0 0xc000 T7-N-BRROM.bin 
BROM magic (eGON.BRM) found!
BROM header starts at 0x3000
BROM header size is 36
BROM boot version is 1100
BROM eGON is 1100
BROM platform is 1633
BROM dumped successfully!
```

The BROM set SP to 0x27ffc in the address 0x00003294 and I am not a good hacker for arm asm, could you please check it again?

[T7-N-BROM.bin.gz](https://github.com/linux-sunxi/sunxi-tools/files/13856991/T7-N-BROM.bin.gz)

2024-01-10 17:43 UTC, apritzel commented
Many thanks for the NBROM dump, that's very helpful!
So the FEL entry point is at 0x20, from there it branches to 0x70, and sets up the two stack pointers very early: the IRQ SP to 0x22000 (stored at 0x2ec), and the SVC SP to 0x27000 (stored at 0x2f0). Since the BROM also contains code for loading from MMC or NAND or SPI flash, there are more routines setting stack pointers, so I think the value you found belongs to other routines?
So with that it looks like just 5K would be enough. Can you check whether the area between 0x27000 and 0x28000 contains any data or is written to by the BROM during FEL operation? Then I guess we can reduce the stack backup buffer to 5K.

2024-01-11 06:54 UTC, qianfan-Zhao commented
@apritzel you are right that the SVC sp is started at 0x27000. We can touch the data between 0x27000 and 0x27c00.

```console
$ ./check.sh 0x27000 0x27fff  
Check region(1K) 0x27000 ...........
Check region(1K) 0x27400 ...........
Check region(1K) 0x27800 ...........
Check region(1K) 0x27C00 usb_bulk_send() ERROR -7: Operation timed out
usb_bulk_send() ERROR -7: Operation timed out
sha1sum doesn't match
```

The swap buffer of T7 is much more like H6, 0x27c00 is someting important and we also can not touch it.

2024-01-11 09:47 UTC, apritzel approved these changes
Awesome, many thanks for checking all the regions, and for the changes! Looks all good now, I also checked the SID maps for overlaps.

2024-01-11 09:48 UTC, merged